#瑞芯微平台独立编译
name: ROCKCHIP

#编译计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean
      PUSHPLUS_TOKEN:
        description: 'Pushplus推送token，用于接收编译完成通知。'
        required: false
        type: string

#权限设置
permissions: write-all

#编译任务
jobs:
  config:
    name: ROCKCHIP
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [ROCKCHIP]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [owrt]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名称
      WRT_SSID: OWRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码地址
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码标识
      WRT_SOURCE: ${{matrix.SOURCE}}
      #自定义插件
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #测试模式
      WRT_TEST: ${{inputs.TEST}}
      #推送通知Token
      PUSHPLUS_TOKEN: ${{inputs.PUSHPLUS_TOKEN}}
