#主流程工作流 - 一键执行全部操作
name: MAIN-FLOW

#CI计划
on:
  #仅手动触发
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  #第一步：清理缓存
  cache_clean:
    name: Cache Clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Cache Clean
        run: gh cache delete --all

  #第二步：清理旧发布和工作流历史
  auto_clean:
    name: Auto Clean
    needs: cache_clean
    runs-on: ubuntu-latest
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0

  #第三步：编译QCA平台固件
  qca_build:
    name: QCA Platforms Build
    needs: auto_clean
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES, IPQ807X-WIFI-YES]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名称
      WRT_SSID: OWRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}

  #第四步：编译其他平台固件
  owrt_build:
    name: Other Platforms Build
    needs: auto_clean
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [MEDIATEK, ROCKCHIP, X86]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [owrt]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名称
      WRT_SSID: OWRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}

  #第五步：构建完成通知
  notify:
    name: Build Complete
    needs: [qca_build, owrt_build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Complete
        run: |
          echo "=== 构建流程已完成 ==="
          echo "缓存清理: ${{ needs.cache_clean.result }}"
          echo "历史清理: ${{ needs.auto_clean.result }}"
          echo "QCA平台构建: ${{ needs.qca_build.result }}"
          echo "其他平台构建: ${{ needs.owrt_build.result }}"